import type { NdaFormData, Party } from "@/lib/nda/types";
import {
  formatConfidentialityTerm,
  formatEffectiveDate,
  formatMndaTerm,
  orPlaceholder,
} from "@/lib/nda/format";

const Clause = ({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) => (
  <section className="clause">
    <h3>{title}</h3>
    <div>{children}</div>
  </section>
);

/**
 * A party's column in the signature block. The signature and date lines are
 * left blank on purpose: they are signed by hand once the document is printed.
 */
const SignatureColumn = ({ party, heading }: { party: Party; heading: string }) => (
  <div className="signature-column">
    <h4>{heading}</h4>
    <dl>
      <dt>Signature</dt>
      <dd className="signature-line" />
      <dt>Print Name</dt>
      <dd>{orPlaceholder(party.printName, "Print name")}</dd>
      <dt>Title</dt>
      <dd>{orPlaceholder(party.title, "Title")}</dd>
      <dt>Company</dt>
      <dd>{orPlaceholder(party.company, "Company")}</dd>
      <dt>Notice Address</dt>
      <dd className="preserve-lines">
        {orPlaceholder(party.noticeAddress, "Email or postal address")}
      </dd>
      <dt>Date</dt>
      <dd className="signature-line" />
    </dl>
  </div>
);

interface NdaDocumentProps {
  data: NdaFormData;
  /** The Standard Terms, pre-rendered to HTML from the repository template. */
  standardTermsHtml: string;
}

/**
 * The finished agreement: a filled-in Cover Page followed by the unmodified
 * Common Paper Standard Terms. This is the only element that prints.
 */
export const NdaDocument = ({ data, standardTermsHtml }: NdaDocumentProps) => (
  <article className="document" id="nda-document">
    <header className="document-header">
      <h1>Mutual Non-Disclosure Agreement</h1>
      <p className="document-note">
        This Mutual Non-Disclosure Agreement (the &ldquo;MNDA&rdquo;) consists of
        this Cover Page and the Common Paper Mutual NDA Standard Terms Version
        1.0, identical to those posted at{" "}
        <a href="https://commonpaper.com/standards/mutual-nda/1.0">
          commonpaper.com/standards/mutual-nda/1.0
        </a>{" "}
        and reproduced in full below. Any modifications are recorded on the
        Cover Page, which controls over conflicts with the Standard Terms.
      </p>
    </header>

    <h2>Cover Page</h2>

    <Clause title="Purpose">
      {/* Line breaks are preserved: the Purpose defines the permitted use of
          Confidential Information under Standard Terms 1 and 2, and is often
          entered as a list. */}
      <p className="preserve-lines">
        {orPlaceholder(data.purpose, "How Confidential Information may be used")}
      </p>
    </Clause>

    <Clause title="Effective Date">
      {formatEffectiveDate(data.effectiveDate)}
    </Clause>

    <Clause title="MNDA Term">{formatMndaTerm(data.mndaTerm)}</Clause>

    <Clause title="Term of Confidentiality">
      {formatConfidentialityTerm(data.confidentialityTerm)}
    </Clause>

    <Clause title="Governing Law &amp; Jurisdiction">
      <p>
        Governing Law: {orPlaceholder(data.governingLaw, "Fill in state")}
      </p>
      <p>
        Jurisdiction:{" "}
        {orPlaceholder(
          data.jurisdiction,
          "Fill in city or county and state",
        )}
      </p>
    </Clause>

    <Clause title="MNDA Modifications">
      {data.modifications.trim() === "" ? (
        <p className="muted">None.</p>
      ) : (
        // Preserved as typed so numbered or line-separated changes keep their
        // shape in the printed agreement.
        <p className="preserve-lines">{data.modifications.trim()}</p>
      )}
    </Clause>

    <p className="signature-intro">
      By signing this Cover Page, each party agrees to enter into this MNDA as of
      the Effective Date.
    </p>

    <div className="signatures">
      <SignatureColumn party={data.partyOne} heading="Party 1" />
      <SignatureColumn party={data.partyTwo} heading="Party 2" />
    </div>

    <h2 className="page-break">Standard Terms</h2>
    <div
      className="standard-terms"
      // The Standard Terms come from the repository's own curated template file,
      // not from user input, and must render with their original markup intact.
      dangerouslySetInnerHTML={{ __html: standardTermsHtml }}
    />

    <footer className="attribution">
      <p>
        Based on the Common Paper Mutual Non-Disclosure Agreement (Version 1.0),
        free to use under{" "}
        <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.
        This document was generated by prelegal: the Cover Page has been
        completed for the parties named above, and the text of the Standard
        Terms is reproduced from Version 1.0 without alteration.
      </p>
    </footer>
  </article>
);
